# Generated by Django 5.0.6 on 2024-05-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-05-30 14:30:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='language',
            field=models.CharField(choices=[('eng', 'Английский'), ('rus', 'Русский')], default='eng', max_length=5, verbose_name='Язык пользователя'),
        ),
    ]
