# Generated by Django 5.0.6 on 2024-05-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_telegramuser_create_at_telegramuser_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='language',
            field=models.CharField(blank=True, choices=[('eng', 'Английский'), ('rus', 'Русский')], default='eng', max_length=5, null=True, verbose_name='Язык пользователя'),
        ),
    ]
