# Generated by Django 5.0.6 on 2024-05-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_telegramuser_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Админ'), ('free_status_user', 'Юзер с ограничениями'), ('paid_status_user', 'Юзер без ограничений')], default='free_status_user', max_length=40, verbose_name='Статус юзера'),
        ),
    ]
